app:
  swagger:
    title: 福生可视化对外提供接口文档
    description: 用于对外提供用户登录、人员签到等数据
    scanPackage: com.fosung.ksh.surface.controller
  session:
    cookieKey: jessionId
  # 权限验证配置
  secure:
    auth:
      enable: true
      urlAuths:
        -
          url : /**
          filter : anon

    referer:
      enable: false

    # 是否允许跨域请求，默认禁止，如果允许跨域的话，需要设置允许的跨域方法及请求头
    cors:
      enable: false

#redis配置地址
spring:
  profiles:
    active: dev

  sleuth:
    sampler:
      percentage: 1


# actuator配置
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

# 端口
server:
  port: 8008



logging:
  config: classpath:logback-spring.xml

