spring:
  zipkin:
    base-url: http://172.16.67.37:8081
  redis:
    database: 1
    port: 6379
    host: 172.16.67.37

#服务注册地址
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://172.16.67.37:8761/eureka/
