spring:
  zipkin:
    base-url: http://192.168.103.188:8081
  redis:
    database: 1
    port: 6379
    host: 10.1.1.147
    password: 123456

#服务注册地址
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
