app:
  dao:
    dataSource:
      url: jdbc:postgresql://10.1.1.147:5432/ksh_meeting?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
      driverClass: org.postgresql.Driver
      username: postgres
      password: 123456
      sql-script-encoding: utf-8

ksh:
  attachment:
    storePath: /Users/wangyihua/projects/visual-meeting/visual-attachment/target/attachment
    downloadPath: http://127.0.0.1:8099/app/attachment/download/{id}

spring:
  redis:
    database: 1
    port: 6379
    host: 10.1.1.147
    password: 123456
  servlet:
    multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 1024Mb
      # 上传多个文件最大值,50Mb,默认10Mb
      max-request-size: 1024Mb

#服务注册地址
eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
