spring:
  zipkin:
    base-url: http://192.168.103.188:8081

#服务注册地址
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#网关代理
zuul:
  routes:
    ksh-ytezb:
      path: /yantai-ezb/**
      url: http://visual.fosung.com:97/yantai-ezb/
