app:
  # 数据源配置信息
  dao:
    dataSource:
      url: jdbc:postgresql://172.16.67.17:5432/ksh_laizhou_duty_monitor?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
      driverClass: org.postgresql.Driver
      username: postgres
      password: lzvisual@123
      sql-script-encoding: utf-8
    mybatis:
      dialect: postgresql
      aliasPackage: com.fosung.ksh

ksh:
  duty:
    cityCodes:
      - 370683
      - 370112
    libId: 1557390531102
    libIds:
      - 1557390531102
      - 1555065189292
      - 1555035860428
      - 1556540851561
      - 1556545884246
      - 1556976001591

#redis配置地址
spring:
  redis:
    database: 1
    port: 6379
    host: 172.16.67.18

  zipkin:
    base-url: http://172.16.67.25:8081


#服务注册地址
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://172.16.67.25:8761/eureka/

# 开启饥饿加载
ribbon:
  eager-load:
    enabled: true
  ConnectTimeout: 10000
  ReadTimeout: 60000
  MaxAutoRetries: 0 #对 第一次 请求 的 服务 的 重试 次数
  MaxAutoRetriesNextServer: 0 #要 重试 的 下一个 服务 的 最大 数量（ 不包括
server:
  tomcat:
    basedir: /tmp/tomcat
