app:
  dao:
    dataSource:
      url: jdbc:postgresql://172.16.67.17:5432/ksh_sys?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
      driverClass: org.postgresql.Driver
      username: postgres
      password: lzvisual@123
      sql-script-encoding: utf-8
    mybatis:
      dialect: postgresql
      aliasPackage: com.fosung.ksh.sys.dao

  # 系统登录页面地址
  secure:
    auth:
      enable: true
      urlAuths:
        -
          url : /**
          filter : anon
    referer:
      enable: false

    # 是否允许跨域请求，默认禁止，如果允许跨域的话，需要设置允许的跨域方法及请求头
    cors:
      enable: false


ksh:
  # 灯塔互联网sso配置
  sso:
    dt:
      enable: true
      clientId: visual-client-ui
      clientSecret: ido85R&Dcenter

  # 简项库地址配置
  sys:
    urls:
      simpleData: http://198.18.66.26:8962/simpledata

#redis配置地址
spring:
  redis:
    database: 1
    port: 6379
    host: 172.16.67.18

  zipkin:
    base-url: http://172.16.67.25:8081


#服务注册地址
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://172.16.67.25:8761/eureka/

# 开启饥饿加载
ribbon:
  eager-load:
    enabled: true
  ConnectTimeout: 10000
  ReadTimeout: 60000
  MaxAutoRetries: 0 #对 第一次 请求 的 服务 的 重试 次数
  MaxAutoRetriesNextServer: 0 #要 重试 的 下一个 服务 的 最大 数量（ 不包括
